# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'News', folder: 'pages', file: 'news.html'}
- {name: 'Biography', folder: 'documentation', file: 'about-zack-browning.html'}
- {name: 'Compositions', folder: 'documentation', file: 'composition-page.html'}
- {name: 'Recordings/Reviews', folder: 'documentation', file: 'recordings.html'}
- {name: 'Martirano Award', folder: 'documentation', file: 'martirano-award.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/zack.browning.338'}
- {icon: 'rss-square', link: 'rss-feed.xml'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related article...'

post_date_prefix: 'Written on'
